CREATE DATABASE IF NOT EXISTS DeepGuard_AI;
USE DeepGuard_AI;

-- Users table for authentication
CREATE TABLE IF NOT EXISTS Users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('user', 'admin') DEFAULT 'user',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Insert default admin account (password: admin123)
-- Hash generated by werkzeug.security.generate_password_hash
INSERT IGNORE INTO Users (username, password_hash, role) 
VALUES ('admin', 'scrypt:32768:8:1$placeholder$admin', 'admin');

CREATE TABLE IF NOT EXISTS MediaMetadata (
    media_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    filename VARCHAR(255) NOT NULL,
    file_size_mb DECIMAL(10, 2),
    upload_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS AnalysisResults (
    analysis_id INT AUTO_INCREMENT PRIMARY KEY,
    media_id INT NOT NULL,
    confidence_score DECIMAL(5, 2) NOT NULL,
    verdict VARCHAR(50) NOT NULL,
    model_used VARCHAR(100),
    FOREIGN KEY (media_id) REFERENCES MediaMetadata(media_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DetectionArtifacts (
    artifact_id INT AUTO_INCREMENT PRIMARY KEY,
    analysis_id INT NOT NULL,
    frame_number INT NOT NULL,
    artifact_type VARCHAR(255),
    FOREIGN KEY (analysis_id) REFERENCES AnalysisResults(analysis_id) ON DELETE CASCADE
);
